# Ansible inventory created from ['/home/tj/projects/sandbox/netlab-test/topology.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ansible_user: admin
ansible_ssh_pass: admin
ansible_network_os: eos
ansible_connection: network_cli
netlab_config_remove:
- no lldp transmit
- no lldp receive
ansible_become: 'yes'
ansible_become_method: enable
netlab_ready:
- ssh
features:
  initial:
    system_mtu: true
    ipv4:
      unnumbered: true
    ipv6:
      lla: true
      use_ra: true
    max_mtu: 9194
    min_mtu: 68
    ra: true
    roles:
    - host
    - router
    - bridge
    mgmt_vrf: true
    generate_mac:
    - ethernet
  bfd: {}
  bgp:
    activate_af: true
    ipv6_lla: true
    local_as: true
    local_as_ibgp: true
    vrf_local_as: true
    import:
    - ospf
    - isis
    - ripv2
    - connected
    - static
    - vrf
    community:
      standard:
      - standard
      - large
      large:
      - large
      extended:
      - extended
      2octet:
      - standard
    confederation: true
  dhcp:
    client:
      ipv4: true
    relay: true
    vrf: true
    server: true
  evpn:
    asymmetrical_irb: true
    bundle:
    - vlan_aware
    irb: true
  gateway:
    protocol:
    - anycast
    - vrrp
  isis:
    circuit_type: true
    import:
    - bgp
    - ospf
    - ripv2
    - connected
    - static
    - vrf
    unnumbered:
      ipv4: true
      ipv6: true
      network: true
  lag:
    mlag:
      peer:
        vlan: 4094
        ifindex: 4094
        ip: 169.254.127.0/31
    passive: true
  mpls:
    6pe: true
    bgp: true
    ldp: true
    vpn: true
  ospf:
    unnumbered: true
    import:
    - bgp
    - isis
    - ripv2
    - connected
    - static
    - vrf
    default:
      policy: true
    password: true
    priority: true
    timers: true
  ripv2:
    ipv4: true
    ipv6: false
    passive: false
  routing:
    policy:
      set:
      - locpref
      - med
      - weight
      - prepend
      - community
      match:
      - prefix
      - nexthop
      - aspath
      - community
    prefix: true
    aspath: true
    community:
      expanded: true
    static:
      vrf: true
      inter_vrf: true
      discard: true
  sr: {}
  stp:
    supported_protocols:
    - stp
    - rstp
    - mstp
    - pvrst
    enable_per_port: true
    port_type: true
  vlan:
    model: l3-switch
    native_routed: true
    subif_name: '{ifname}.{subif_index}'
    svi_interface_name: Vlan{vlan}
  vrf:
    ospfv2: true
    ospfv3: true
    bgp: true
    isis: true
  vxlan: {}
